apiVersion: batch/v1
kind: Job
metadata:
  name: job-dataset-list
spec:
  template:
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            ls -l /opt/coco2017/annotations &&
            rm -rf /opt/coco2017 &&
            ls -l /opt
        volumeMounts:
        - name: data-volume
          mountPath: /opt
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-dataset
      restartPolicy: Never
