apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model-output
  annotations:
    purpose: model-output
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/model-output
