apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-model-output
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      purpose: model-output
  resources:
    requests:
      storage: 20Gi
