apiVersion: batch/v1
kind: Job
metadata:
  name: job-dataset-download-only
spec:
  template:
    spec:
      containers:
      - name: coco2017-dataset-downloader
        image: mtamasdocker/coco2017-dataset-downloader:3.0
        env:
        - name: DATASET_DIR
          value: "/opt/ml/input/data/coco2017"
        - name: DATASET_DOWNLOAD_SIZE_PERCENT
          value: "1"
        - name: CLEAN_DATASET_DIR
          value: "No"
        - name: RECREATE_ANNONATIONS
          value: "Yes"
        volumeMounts:
        - name: pv-dataset
          mountPath: /opt/ml/input/data/
      volumes:
      - name: pv-dataset
        persistentVolumeClaim:
          claimName: pvc-dataset
      restartPolicy: Never
