apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    component: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        component: client
    spec:
      containers:
      - name: client
        image: mtamasdocker/idea-research-dino-client-app:0.1
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://service-inference:8080/inference"
        - name: PORT
          value: "80"
