apiVersion: v1
kind: Service
metadata:
  name: service-client
spec:
  selector:
    app: client
    component: client
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
