# Use an official NVIDIA CUDA runtime as a parent image
FROM nvidia/cuda:11.7.0-runtime-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive

# Update and upgrade Ubuntu packages
RUN apt-get update && apt-get upgrade -y

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.8 python3.8-dev python3-pip

# Set Python 3.7 as the default Python version
RUN ln -sf /usr/bin/python3.8 /usr/bin/python

# Install necessary packages
RUN apt-get install -y libsm6 libxext6 libxrender-dev

# Set the working directory
WORKDIR /app

# Copy inference files
COPY inference.tgz /app

RUN tar -xzf inference.tgz -C /app

WORKDIR /app/inference

COPY checkpoint0023_4scale.pth /app/inference/assets/

# Set the environment variables
ENV MODEL_CONFIG_PATH assets/DINO_4scale.py

ENV MODEL_CHECKPOINT_NAME assets/checkpoint0023_4scale.pth

ENV PORT 30001

# Install necessary python packages
RUN pip install torch==1.9.0 torchvision==0.10.0  numpy Pillow fastapi uvicorn

RUN pip install termcolor addict cython submitit yapf pycocotools timm scipy

RUN pip install python-multipart

# Set the entry point for the container
ENTRYPOINT ["python", "inference.py"]
