---
- name: Install Docker and NVIDIA Container Toolkit
  hosts: localhost
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Download Docker installation script
      get_url:
       url: https://get.docker.com
       dest: /tmp/install_docker.sh
      when: docker_check.rc != 0

    - name: Run Docker installation script
      shell: sh /tmp/install_docker.sh
      args:
        warn: no
      when: docker_check.rc != 0

    - name: Enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Import NVIDIA Container Toolkit GPG key
      shell: >
        distribution=$(. /etc/os-release; echo $ID$VERSION_ID) &&
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg  --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg --yes &&
        curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list |
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' |
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NVIDIA Container Toolkit
      apt:
        name: nvidia-container-toolkit
        state: present

    - name: Configure NVIDIA runtime for Docker
      command: nvidia-ctk runtime configure --runtime=docker
      args:
        warn: no

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
