apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dataset
  annotations:
    purpose: dataset
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/dataset
