apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dataset
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      purpose: dataset
  resources:
    requests:
      storage: 40Gi
