apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dataset
  annotations:
    purpose: dataset
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /opt/dataset
